
import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { payrollApi } from '../api/payroll';
import { Card, Button, Badge, Input, Select } from '../components/ui';
import { DataTable } from '../components/shared/DataTable';
import { Download, FileSpreadsheet, Wallet, Search } from 'lucide-react';
import { saveAs } from 'file-saver';
import { format } from 'date-fns';

const FinancePage: React.FC = () => {
    // 1. Fetch report history
    const { data: reports, isLoading } = useQuery({
        queryKey: ['payroll-reports'],
        queryFn: () => payrollApi.listReports().then(res => res.data)
    });

    const [searchQuery, setSearchQuery] = useState('');
    const [filterYear, setFilterYear] = useState('ALL');

    const years = useMemo(() => {
        if (!reports) return [{ label: 'All Years', value: 'ALL' }];
        const uniqueYears = Array.from(new Set(reports.map((r: any) => r.year)));
        return [
            { label: 'All Years', value: 'ALL' },
            ...uniqueYears.sort().reverse().map(y => ({ label: String(y), value: String(y) }))
        ];
    }, [reports]);

    const filteredReports = useMemo(() => {
        if (!reports) return [];
        return reports.filter((report: any) => {
            const matchesYear = filterYear === 'ALL' || String(report.year) === filterYear;
            const searchLower = searchQuery.toLowerCase();
            const generatorName = report.createdBy?.employee?.name || 'System';
            const monthName = format(new Date(0, report.month - 1), 'MMMM').toLowerCase();
            const matchesSearch = generatorName.toLowerCase().includes(searchLower) || monthName.includes(searchLower);
            return matchesYear && matchesSearch;
        });
    }, [reports, filterYear, searchQuery]);

    const handleDownload = async (reportId: number, month: number, year: number) => {
        try {
            const response = await payrollApi.downloadReport(reportId);
            const blob = new Blob([response.data], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
            saveAs(blob, `Payroll_Report_${year}_${month}.xlsx`);
        } catch (error) {
            console.error('Download failed', error);
            alert('Failed to download report. Please try again.');
        }
    };

    const columns = [
        { 
            key: 'month',
            header: 'Period', 
            render: (row: any) => (
                <div className="font-semibold text-gray-900">
                    {format(new Date(0, row.month - 1), 'MMMM')} {row.year}
                </div>
            )
        },
        { 
            key: 'createdBy',
            header: 'Generated By', 
            render: (row: any) => row.createdBy?.employee?.name || 'System'
        },
        { 
            key: 'createdAt',
            header: 'Sent Date', 
            render: (row: any) => format(new Date(row.createdAt), 'MMM dd, yyyy HH:mm')
        },
        { 
            key: 'status',
            header: 'Status', 
            render: (row: any) => (
                <Badge variant={row.status === 'AMENDED' ? 'warning' : 'approved'}>
                    {row.status}
                </Badge>
            )
        },
        {
            key: 'actions',
            header: 'Actions',
            render: (row: any) => (
                <Button 
                    variant="secondary"
                    size="sm"
                    onClick={() => handleDownload(row.id, row.month, row.year)}
                >
                    <Download className="w-4 h-4 mr-2" />
                    Download XLSX
                </Button>
            )
        }
    ];

    return (
        <div className="p-6 space-y-6 max-w-7xl mx-auto">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold text-gray-900 flex items-center gap-2">
                        <Wallet className="text-emerald-600" />
                        Finance Payroll Dashboard
                    </h1>
                    <p className="text-gray-500">View and download payroll reports sent by the HR department.</p>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <Card className="p-6 bg-emerald-50/50 border-emerald-100">
                    <div className="text-emerald-700 text-xs font-bold uppercase tracking-wider mb-2">Total Reports</div>
                    <div className="text-3xl font-bold text-emerald-900">{reports?.length || 0}</div>
                </Card>
                <Card className="p-6 bg-blue-50/50 border-blue-100">
                    <div className="text-blue-700 text-xs font-bold uppercase tracking-wider mb-2">Last Received</div>
                    <div className="text-lg font-bold text-blue-900">
                        {reports?.[0] ? `${format(new Date(0, reports[0].month - 1), 'MMMM')} ${reports[0].year}` : 'N/A'}
                    </div>
                </Card>
            </div>

            <Card className="overflow-hidden border-gray-200">
                <div className="p-4 border-b border-gray-100 bg-gray-50/50 flex flex-col sm:flex-row gap-4 items-center justify-between">
                    <div className="flex items-center gap-2">
                        <FileSpreadsheet className="w-5 h-5 text-gray-400" />
                        <span className="font-semibold text-gray-700">Available Reports</span>
                    </div>
                    <div className="flex items-center gap-3 w-full sm:w-auto">
                        <div className="relative w-full sm:w-64">
                            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                            <Input 
                                placeholder="Search month or name..." 
                                className="pl-9"
                                value={searchQuery}
                                onChange={(e: any) => setSearchQuery(e.target.value)}
                            />
                        </div>
                        <div className="w-32">
                            <Select 
                                options={years}
                                value={filterYear}
                                onChange={(e: any) => setFilterYear(e.target.value)}
                            />
                        </div>
                    </div>
                </div>
                <DataTable 
                    columns={columns} 
                    data={filteredReports} 
                    isLoading={isLoading} 
                    keyExtractor={(row: any) => row.id}
                />
            </Card>
        </div>
    );
};

export default FinancePage;
